export enum NotificationType {
  CAMPAIGN_ALMOST_COMPLETE = 'CAMPAIGN_ALMOST_COMPLETE',
  CAMPAIGN_SUCCESSFUL = 'CAMPAIGN_SUCCESSFUL',
  CAMPAIGN_FAILED = 'CAMPAIGN_FAILED',
  PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  PRODUCT_APPROVED = 'PRODUCT_APPROVED',
  PRODUCT_REJECTED = 'PRODUCT_REJECTED',
}
